CrustEngine: Crust::Matrix< T, H, W > Class Template Reference
Crust::Matrix< T, H, W > Class Template Reference
Represents the mathematical matrix and is able to preform matrix calculations.
#include <Matrix.h>
Public Member Functions
Matrix ()
Matrix (T p_val)
If width or height argument is zero then no space for matrix's array will be allocated.
uint16_t height () const
Get the height of the matrix.
uint16_t width () const
Get the width of the matrix.
void reset (T p_val)
Reset all elements in matrix to the given value.
void makeIdentity ()
Make this matrix an identity matrix.
template<typename D >
Matrix< T, H, W > & operator= (const Eigen::MatrixBase< D > &other)
Detailed Description
template<typename T, int H, int W>
class Crust::Matrix< T, H, W >
Represents the mathematical matrix and is able to preform matrix calculations.
This matrix class assumes that x value is the number of a column and y value is the number of a row. This means that matrix[3][2] is value in 3rd row and 2nd column. Also height says how many rows there are and width says how many columns there are.
Template Parameters
T Types of values held in this matrix.
H Amount of rows in this matrix.
W Amount of columns in this matrix.
Constructor & Destructor Documentation
Matrix() [1/2]
template<typename T , int H, int W> Crust::Matrix< T, H, W >::Matrix () inline
: Eigen::Matrix<T, H, W>() {};
Matrix() [2/2]
template<typename T , int H, int W> Crust::Matrix< T, H, W >::Matrix (T p_val) explicit
If width or height argument is zero then no space for matrix's array will be allocated.
Parameters
defaultVal The value that will be placed on each position in matrix.
                                   : Eigen::Matrix<T, H, W>() {
        reset(p_val);
    }
References Crust::Matrix< T, H, W >::reset().
Member Function Documentation
height()
template<typename T , int H, int W> uint16_t Crust::Matrix< T, H, W >::height () const inline
Get the height of the matrix.
{ return (*this).rows(); };
Referenced by Crust::Logger::log().
makeIdentity()
template<typename T , int H, int W> void Crust::Matrix< T, H, W >::makeIdentity
Make this matrix an identity matrix.
{
        for (int i = 0; i < W; i++) {
            for (int j = 0; j < H; j++) {
                if (i == j) {
                    (*this)(i, j) = 1;
                } else {
                    (*this)(i, j) = 0;
                }
            }
        }
    }
operator=()
template<typename T , int H, int W> template<typename D > Matrix< T, H, W > & Crust::Matrix< T, H, W >::operator= (const Eigen::MatrixBase< D > & other) inline
        {
            this->Eigen::Matrix<T, H, W>::operator=(other);
            return *this;
        }
reset()
template<typename T , int H, int W> void Crust::Matrix< T, H, W >::reset (T p_val)
Reset all elements in matrix to the given value.
Parameters
p_val The value that will be placed on each position in matrix.
{
        for (int i = 0; i < W; i++) {
            for (int j = 0; j < H; j++) {
                (*this)(i, j) = p_val;
            }
        }
    }
Referenced by Crust::Matrix< T, H, W >::Matrix().
width()
template<typename T , int H, int W> uint16_t Crust::Matrix< T, H, W >::width () const inline
Get the width of the matrix.
{ return (*this).cols(); };
Referenced by Crust::Logger::log().
The documentation for this class was generated from the following file:
/Users/karolborecki/Desktop/CrustEngine/engine/inc/math/Matrix.h