CrustEngine: Crust::Logger Class Reference
Crust::Logger Class Reference
Static class allowing to log with certain color and style on classic console with well-known printf() arguments.
#include <Logger.h>
Public Types
enum FontColor {
WHITE = 0 , GREY = 37 , LIGHT_BLUE = 36 , PINK = 35 ,
GREEN = 32 , BLUE = 34 , RED = 31 , YELLOW = 33
}
representing console color codes.
enum FontStyle { NORMAL = 0 , BOLD = 1 }
Enumeration representing console font styles codes.
Static Public Member Functions
static void error (const char *p_format,...)
Logs onto the console in red color.
static void warning (const char *p_format,...)
Logs onto the console in yellow color.
static void info (const char *p_format,...)
Logs onto the console in blue color.
static void log ()
Prints empty line onto the console.
static void log (const char *p_format,...)
Logs onto the console with standard printf-like interface.
static void log (int p_color_code, const char *p_format,...)
Logs onto the console in specified colorCode color.
static void logInline (const char *p_format,...)
Logs onto the console.
template<class T , int H, int W>
static void log (const char *p_info, const Matrix< T, H, W > &p_matrix)
Logs matrix onto the console.
template<class T >
static void log (const char *p_info, const Vector3< T > &p_vector)
Logs 3 dimensional vector onto the console.
template<class T >
static void log (const char *p_info, const Vector4< T > &p_vector)
Logs 4 dimensional vector onto the console.
static void setFont (int p_color_code, int p_style_code)
Sets console color to colorCode and console font style to styleCode;.
static void setFont (int p_color_code)
Sets console color to colorCode.
Detailed Description
Static class allowing to log with certain color and style on classic console with well-known printf() arguments.
Member Enumeration Documentation
FontColor
enum Crust::Logger::FontColor
representing console color codes.
Enumerator
WHITE
GREY
LIGHT_BLUE
PINK
GREEN
BLUE
RED
YELLOW
        {
            WHITE = 0,
            GREY = 37,
            LIGHT_BLUE = 36,
            PINK = 35,
            GREEN = 32,
            BLUE = 34,  /* RESERVED FOR INFOS */
            RED = 31,   /* RESERVED FOR WARNINGS */
            YELLOW = 33 /* RESERVED FOR ERRORS */
        };
FontStyle
enum Crust::Logger::FontStyle
Enumeration representing console font styles codes.
Enumerator
NORMAL
BOLD
        {
            NORMAL = 0,
            BOLD = 1
        };
Member Function Documentation
error()
void Crust::Logger::error (const char * p_format, ...) inline static
Logs onto the console in red color.
    {
        setFont(Logger::FontColor::RED);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        printf("\n");
        va_end(args);
        setFont(FontColor::WHITE);
    }
References RED, setFont(), and WHITE.
Referenced by Crust::ExceptionsHandler::throwError().
info()
void Crust::Logger::info (const char * p_format, ...) inline static
Logs onto the console in blue color.
    {
        setFont(FontColor::BLUE);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        printf("\n");
        va_end(args);
        setFont(FontColor::WHITE);
    }
References BLUE, setFont(), and WHITE.
log() [1/6]
void Crust::Logger::log () inline static
Prints empty line onto the console.
    {
        printf("\n");
    }
Referenced by log().
log() [2/6]
void Crust::Logger::log (const char * p_format, ...) inline static
Logs onto the console with standard printf-like interface.
    {
        setFont(FontColor::WHITE);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        printf("\n");
        va_end(args);
    }
References setFont(), and WHITE.
log() [3/6]
template<typename T , int H, int W> void Crust::Logger::log (const char * p_info, const Matrix< T, H, W > & p_matrix) static
Logs matrix onto the console.
{
        log("%s", p_info);
        for (int y = 0; y < p_matrix.height(); ++y) {
            for (int x = 0; x < p_matrix.width(); ++x) {
                logInline("%.2f ", p_matrix(y, x));
            }
            log();
        }
        logInline("[%zu x %zu] \n", p_matrix.width(), p_matrix.height());
    }
References Crust::Matrix< T, H, W >::height(), log(), logInline(), and Crust::Matrix< T, H, W >::width().
log() [4/6]
template<typename T > void Crust::Logger::log (const char * p_info, const Vector3< T > & p_vector) static
Logs 3 dimensional vector onto the console.
{
        log("%s", p_info);
        logInline("[%.2f, %.2f, %.2f]\n", v.x(), v.y(), v.z());
    }
References log(), and logInline().
log() [5/6]
template<class T > void Crust::Logger::log (const char * p_info, const Vector4< T > & p_vector) static
Logs 4 dimensional vector onto the console.
{
        log("%s", p_info);
        logInline("[%.2f, %.2f, %.2f, %.2f]\n", p_vector.x(), p_vector.y(), p_vector.z(), p_vector.w());
    }
References log(), and logInline().
log() [6/6]
void Crust::Logger::log (int p_color_code, const char * p_format, ...) inline static
Logs onto the console in specified colorCode color.
    {
        setFont(p_color_code);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        printf("\n");
        va_end(args);
        setFont(FontColor::WHITE);
    }
References setFont(), and WHITE.
logInline()
void Crust::Logger::logInline (const char * p_format, ...) inline static
Logs onto the console.
    {
        setFont(FontColor::WHITE);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        va_end(args);
    }
References setFont(), and WHITE.
Referenced by log().
setFont() [1/2]
void Crust::Logger::setFont (int p_color_code) inline static
Sets console color to colorCode.
    {
        setFont(colorCode, FontStyle::NORMAL);
    }
References NORMAL, and setFont().
setFont() [2/2]
void Crust::Logger::setFont (int p_color_code, int p_style_code) inline static
Sets console color to colorCode and console font style to styleCode;.
    {
        printf("\033[%dm", Logger::FontColor::WHITE);
        printf("\033[%dm", p_style_code);
        printf("\033[%dm", p_color_code);
    }
References WHITE.
Referenced by error(), info(), log(), logInline(), setFont(), and warning().
warning()
void Crust::Logger::warning (const char * p_format, ...) inline static
Logs onto the console in yellow color.
    {
        setFont(FontColor::YELLOW);
        va_list args;
        va_start(args, p_format);
        vprintf(p_format, args);
        printf("\n");
        va_end(args);
        setFont(FontColor::WHITE);
    }
References setFont(), WHITE, and YELLOW.
Referenced by Crust::ExceptionsHandler::throwWarning().
The documentation for this class was generated from the following file:
/Users/karolborecki/Desktop/CrustEngine/engine/inc/logging/Logger.h