CrustEngine: Crust::TimeProvider Class Reference
Crust::TimeProvider Class Reference
Class providing timing data in the engine.
#include <TimeProvider.h>
Public Member Functions
TimeProvider ()=default
virtual ~TimeProvider ()=default
void onFrameStart ()
Method called on each window's frame start.
void onFrameEnd ()
Method called on each window's frame end.
double getFPS () const
Returns current frames per seconds value based on last frame time.
double getAverageFPS () const
Returns current average frames per seconds value based on all frames.
double getDeltaTime_s () const
Returns last frame time in seconds.
double getDeltaTime_ms () const
Returns last frame time in miliseconds.
double getAverageFrameTime_s () const
Returns average frame time from engine start in seconds.
Static Public Member Functions
static double getTime_ms ()
Returns time from engine's core start in milliseconds.
static double getTime_s ()
Returns time from engine's core start in seconds.
static void onEngineStart ()
Method called on engine's core start.
Static Public Attributes
static constexpr double MILISECONDS_TO_SECONDS {0.001}
Private Attributes
double m_frame_delta_time_ms { 0.0 }
Time that last frame took to complete.
uint32_t m_frames_passed { 0 }
Amount of frames that RenderWindow did from it start.
std::chrono::steady_clock::time_point m_last_frame_start_time_point
Last frame saved time point at which it started.
Static Private Attributes
static std::chrono::steady_clock::time_point m_engine_start_time_point
Engine's core start time point saved in TimeProvider::OnEngineStart.
Detailed Description
Class providing timing data in the engine.
Constructor & Destructor Documentation
TimeProvider()
Crust::TimeProvider::TimeProvider () default
~TimeProvider()
virtual Crust::TimeProvider::~TimeProvider () virtual default
Member Function Documentation
getAverageFPS()
double Crust::TimeProvider::getAverageFPS () const inline
Returns current average frames per seconds value based on all frames.
Returns
Returns value of 1.0 / TimeProvider::GetAverageFrameTime_s.
{ return 1 / getAverageFrameTime_s(); }
References getAverageFrameTime_s().
getAverageFrameTime_s()
double Crust::TimeProvider::getAverageFrameTime_s () const inline
Returns average frame time from engine start in seconds.
Returns
TimeProvider::getTimeS / #framesPassed;
{ return getTime_s() / m_frames_passed; }
References getTime_s(), and m_frames_passed.
Referenced by getAverageFPS().
getDeltaTime_ms()
double Crust::TimeProvider::getDeltaTime_ms () const inline
Returns last frame time in miliseconds.
{ return m_frame_delta_time_ms; }
References m_frame_delta_time_ms.
Referenced by getDeltaTime_s().
getDeltaTime_s()
double Crust::TimeProvider::getDeltaTime_s () const inline
Returns last frame time in seconds.
{ return getDeltaTime_ms() * MILISECONDS_TO_SECONDS; }
References getDeltaTime_ms(), and MILISECONDS_TO_SECONDS.
Referenced by getFPS().
getFPS()
double Crust::TimeProvider::getFPS () const inline
Returns current frames per seconds value based on last frame time.
{ return 1 / getDeltaTime_s(); }
References getDeltaTime_s().
getTime_ms()
double Crust::TimeProvider::getTime_ms () static
Returns time from engine's core start in milliseconds.
    {
        return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - m_engine_start_time_point).count();
    }
References m_engine_start_time_point.
Referenced by getTime_s().
getTime_s()
double Crust::TimeProvider::getTime_s () inline static
Returns time from engine's core start in seconds.
{ return getTime_ms() * MILISECONDS_TO_SECONDS; }
References getTime_ms(), and MILISECONDS_TO_SECONDS.
Referenced by getAverageFrameTime_s().
onEngineStart()
void Crust::TimeProvider::onEngineStart () inline static
Method called on engine's core start.
Saves engine's core start time point.
See also
Core.hpp
{ m_engine_start_time_point = std::chrono::steady_clock::now(); }
References m_engine_start_time_point.
onFrameEnd()
void Crust::TimeProvider::onFrameEnd ()
Method called on each window's frame end.
Saves time point of frame end to calculate how long this frame took.
    {
        m_frame_delta_time_ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - m_last_frame_start_time_point).count();
        m_frames_passed++;
    }
References m_frame_delta_time_ms, m_frames_passed, and m_last_frame_start_time_point.
onFrameStart()
void Crust::TimeProvider::onFrameStart ()
Method called on each window's frame start.
Saves time point of frame start to calculate how long this frame will take.
    {
        m_last_frame_start_time_point = std::chrono::steady_clock::now();
    }
References m_last_frame_start_time_point.
Member Data Documentation
m_engine_start_time_point
std::chrono::steady_clock::time_point Crust::TimeProvider::m_engine_start_time_point inline static private
Engine's core start time point saved in TimeProvider::OnEngineStart.
Referenced by getTime_ms(), and onEngineStart().
m_frame_delta_time_ms
double Crust::TimeProvider::m_frame_delta_time_ms { 0.0 } private
Time that last frame took to complete.
Referenced by getDeltaTime_ms(), and onFrameEnd().
m_frames_passed
uint32_t Crust::TimeProvider::m_frames_passed { 0 } private
Amount of frames that RenderWindow did from it start.
Referenced by getAverageFrameTime_s(), and onFrameEnd().
m_last_frame_start_time_point
std::chrono::steady_clock::time_point Crust::TimeProvider::m_last_frame_start_time_point private
Last frame saved time point at which it started.
Referenced by onFrameEnd(), and onFrameStart().
MILISECONDS_TO_SECONDS
constexpr double Crust::TimeProvider::MILISECONDS_TO_SECONDS {0.001} static constexpr
Referenced by getDeltaTime_s(), and getTime_s().
The documentation for this class was generated from the following file:
/Users/karolborecki/Desktop/CrustEngine/engine/inc/utils/TimeProvider.h